version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: api_express
    image: postgres:14-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=geferson
      - POSTGRES_PASSWORD=gel881206
      - POSTGRES_DB=entrega2
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

